Fixed code for right context equal to 0
desh2608/gss pull request #38
Opened 2023-07-19 11:32 UTC by marcinwitkowski

When `right_context` is set to 0 (which is its default value in function args) the line changed in this PR becomes:
```
x_hat = x_hat[:, left_context:-0]
```
which basically makes `x_hat` empty matrix of size (number_of_channels,0). This conditioning prevents from this.

2023-07-19 14:17 UTC, desh2608 commented
Thanks! For the case when `right_context` is negative, I think it is better to just set it to 0 and raise a warning to inform the user about it, instead of raising an error.

2023-07-19 22:30 UTC, marcinwitkowski commented
@desh2608 , changed as you suggested. Please take a look now.

2023-07-20 05:47 UTC, desh2608 requested changes
Few more changes and should be good to go.

2023-07-20 05:47 UTC, desh2608 commented on gss/core/enhancer.py
> +import warnings
You can use `logging.warning()` instead.

2023-07-20 05:47 UTC, desh2608 commented on gss/core/enhancer.py
> +logging.captureWarnings(True)
This is not required if you make the above change.

2023-07-20 05:47 UTC, desh2608 commented on gss/core/enhancer.py
> +            warnings.warn(f"Right context is less or equal to zero. Only left context is used.")
Raise a warning only if < 0, since right_context=0 is not an error case.

2023-07-20 07:09 UTC, marcinwitkowski commented on gss/core/enhancer.py
> +import warnings
Correct. I read misleading post on Stack Overflow that using `logging.captureWarning()`, the warning will be raised in a typical way  (and may be caught by a user) **and** logged at the same time, which is not true, as the flag redirects the warning to logging according to [logging documentation](https://docs.python.org/3/library/logging.html#logging.captureWarnings). Thanks for catching that!

2023-07-20 13:45 UTC, desh2608 approved these changes

2023-07-20 13:46 UTC, merged